# Generated by Django 5.2.3 on 2025-06-17 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_word', '0002_language_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alternativeimage',
            name='main_image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alt_imgs', to='image_word.image'),
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='image_word.image'),
        ),
    ]
